### ISSUE TITLE
InvalidNeuronId

### ISSUE THREAD

**Issue by letmejustputthishere** [dfinity/sns-testing#12]
bash-3.2$ ./register_dapp.sh q4eej-kyaaa-aaaaa-aaaha-cai
Using identity: "default".
Added as controller of "q4eej-kyaaa-aaaaa-aaaha-cai": sgymv-uiaaa-aaaaa-aaaia-cai
Error: InvalidNeuronId: Could not convert NeuronId to Subaccount could not convert slice to array

**Comment by mraszyk** [comment]
Does the SNS yaml file you used when invoking `deploy_sns.sh` specify a developer neuron for your current DFX identity? The yaml file should either define
```
       developer_neurons:
         - controller: aaaaa-aa
```
in which case `deploy_sns.sh` replaces the principal `aaaaa-aa` with your current DFX identity or contain your current DFX identity.

**Comment by letmejustputthishere** [comment]
Thanks for the reply!
