### ISSUE TITLE
Decentralisation swap not visible in NNS UI

### ISSUE THREAD

**Issue by letmejustputthishere** [dfinity/sns-testing#16]
Initially I can't see the SNS swap, only after a while it eventually pops up. I can participate via the shell scripts without hiccups. Reloading the page did not help.

**Comment by mraszyk** [comment]
This is related to the SNS aggregator canister taking some time to discover the new SNS and include it in the certified asset pulled by the NNS frontend dapp. As long as you see the SNS in the launchpad after a couple of minutes latest, it's expected behavior.

**Comment by letmejustputthishere** [comment]
Got it, maybe it's worth mentioning that in the docs?
