### ISSUE TITLE
While running locally, I can't create local internet identity

### ISSUE THREAD

**Issue by CodingFu** [dfinity/sns-testing#61]
I'm running on mac m3

Steps for reproduce:

1.

```
bash install.sh
```

2.

```
DX_NET_JSON="${HOME}/.config/dfx/networks.json"
mkdir -p "$(dirname "${DX_NET_JSON}")"
cp "$DX_NET_JSON" "${DX_NET_JSON}.tmp" 2>/dev/null
echo '{
   "local": {
      "bind": "0.0.0.0:8080",
      "type": "ephemeral",
      "replica": {
         "subnet_type": "system",
         "port": 8000
      }
   }
}' > "${DX_NET_JSON}"
./bin/dfx start --clean; \
mv "${DX_NET_JSON}.tmp" "$DX_NET_JSON" 2>/dev/null 
```

3. (in new terminal tab)
```
./setup_locally.sh
```

When I visit 
http://qsgjb-riaaa-aaaaa-aaaga-cai.localhost:8080/

and then click 'sign in with internet Identity'

I get redirected to: http://qhbym-qaaaa-aaaaa-aaafq-cai.localhost:8080/#authorize

And, once I try to create an account I see an error:

<img width="923" alt="Screenshot 2024-03-27 at 10 19 19 AM" src="https://github.com/dfinity/sns-testing/assets/1714573/7bd60047-69b8-4d84-96fc-ead193de85aa">

**Comment by letmejustputthishere** [comment]
I experience the same issue.

**Comment by anchpop** [comment]
@letmejustputthishere @CodingFu I just created an MR that should address this issue. Please try it again and leave a comment here if it is not resolved!

**Comment by letmejustputthishere** [comment]
problem resolved, thank you for fixing this!
