### ISSUE TITLE
curl: (35) Recv failure: Connection reset by peer

### ISSUE THREAD

**Issue by letmejustputthishere** [dfinity/sns-testing#63]
when executing `setup_locally.sh` the following error appears a number of times. getting to download all the files requires multiple tries.

**Comment by mraszyk** [comment]
> getting to download all the files requires multiple tries.

this might be due to redirects; does the script succeed after all?

**Comment by letmejustputthishere** [comment]
yes it does, but only after multiple retries

**Comment by letmejustputthishere** [comment]
i just ran the steps again but cannot reproduce the issue, maybe it was just a temporary problem. will close this until it appears again and i can provide more details
